### ISSUE TITLE
Load WebAssembly file directly inside mod.js

### ISSUE THREAD

**Issue by nruspantini** [cacticouncil/minetest#1]
## Problem

Currently, with WasmInjector, the bytes of a WebAssembly file are injected into the mod.js file at runtime. But after running the executable, the changes to mod.js need to be manually reverted.

## Solutions

Either:
- Load WebAssembly file directly inside mod.js
- Automatically revert changes made to mod.js after mod is loaded

**Comment by logandgsmith** [comment]
Added in PR #5 !
